-- FIX SUPABASE SCHEMA
-- Run this in the Supabase SQL Editor to add any missing columns and tables

DO $$ 
BEGIN
    -- 1. Ensure user_profiles has all columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='branch') THEN
        ALTER TABLE public.user_profiles ADD COLUMN branch TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='academic_year') THEN
        ALTER TABLE public.user_profiles ADD COLUMN academic_year TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='user_status') THEN
        ALTER TABLE public.user_profiles ADD COLUMN user_status TEXT CHECK (user_status IN ('active', 'disabled')) DEFAULT 'active';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='cgpa') THEN
        ALTER TABLE public.user_profiles ADD COLUMN cgpa DECIMAL(4, 2) DEFAULT 0.00;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='resume_link') THEN
        ALTER TABLE public.user_profiles ADD COLUMN resume_link TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='skills') THEN
        ALTER TABLE public.user_profiles ADD COLUMN skills TEXT[];
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_profiles' AND column_name='experience_years') THEN
        ALTER TABLE public.user_profiles ADD COLUMN experience_years INTEGER DEFAULT 0;
    END IF;

    -- 2. Ensure events table exists
    CREATE TABLE IF NOT EXISTS public.events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        venue TEXT,
        start_time TIMESTAMPTZ,
        end_time TIMESTAMPTZ,
        qr_refresh_interval INTEGER DEFAULT 10,
        created_by UUID REFERENCES public.user_profiles(id),
        entry_window_mins INTEGER DEFAULT 15,
        exit_window_mins INTEGER DEFAULT 15,
        attendance_phase TEXT DEFAULT 'CLOSED',
        session_state TEXT DEFAULT 'DRAFT',
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- 3. Ensure placement_drives has all columns
    CREATE TABLE IF NOT EXISTS public.placement_drives (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        company_name TEXT NOT NULL,
        role TEXT NOT NULL,
        job_type TEXT CHECK (job_type IN ('FULL_TIME', 'INTERNSHIP', 'BOTH')),
        stipend_ctc TEXT,
        description TEXT,
        deadline TIMESTAMPTZ NOT NULL,
        industry TEXT,
        location TEXT,
        about_company TEXT,
        selection_process TEXT,
        bond_details TEXT,
        criteria_details TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        status TEXT DEFAULT 'OPEN'
    );

    -- 4. Ensure qr_sessions has event_id column
    CREATE TABLE IF NOT EXISTS public.qr_sessions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token TEXT NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE
    );
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='qr_sessions' AND column_name='event_id') THEN
        ALTER TABLE public.qr_sessions ADD COLUMN event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE;
    END IF;

    -- 5. Complete remaining tables
    CREATE TABLE IF NOT EXISTS public.eligibility_rules (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        drive_id BIGINT REFERENCES public.placement_drives(id) ON DELETE CASCADE,
        min_cgpa NUMERIC DEFAULT 0,
        allowed_branches TEXT[] DEFAULT '{}',
        allowed_years TEXT[] DEFAULT '{}'
    );

    CREATE TABLE IF NOT EXISTS public.drive_applications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        drive_id BIGINT REFERENCES public.placement_drives(id) ON DELETE CASCADE,
        student_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
        status TEXT DEFAULT 'APPLIED',
        applied_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(drive_id, student_id)
    );

    CREATE TABLE IF NOT EXISTS public.attendance_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
        event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
        qr_session_id BIGINT REFERENCES public.qr_sessions(id) ON DELETE SET NULL,
        device_hash TEXT,
        status TEXT DEFAULT 'ENTRY',
        scan_time TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(user_id, event_id)
    );

    CREATE TABLE IF NOT EXISTS public.assessment_eligibility (
        assessment_id BIGINT REFERENCES public.assessments(id) ON DELETE CASCADE,
        user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
        PRIMARY KEY (assessment_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS public.assessment_allocations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        assessment_id BIGINT REFERENCES public.assessments(id) ON DELETE CASCADE,
        user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
        lab_id BIGINT REFERENCES public.labs(id),
        seat_number INTEGER NOT NULL,
        allocated_at TIMESTAMPTZ DEFAULT NOW(),
        UNIQUE(assessment_id, user_id)
    );

END $$;

-- Reload schema cache
NOTIFY pgrst, 'reload schema';
