-- SUPABASE SETUP SCRIPT
-- Run this in the Supabase SQL Editor

-- 1. Create user_profiles table
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    enrollment_no TEXT UNIQUE,
    branch TEXT,
    role TEXT CHECK (role IN ('student', 'admin', 'super_admin')) DEFAULT 'student',
    academic_year TEXT,
    user_status TEXT CHECK (user_status IN ('active', 'disabled')) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    cgpa DECIMAL(4, 2) DEFAULT 0.00,
    resume_link TEXT,
    skills TEXT[],
    experience_years INTEGER DEFAULT 0
);

-- 2. Create placement_drives table
CREATE TABLE IF NOT EXISTS public.placement_drives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    role TEXT NOT NULL,
    job_type TEXT CHECK (job_type IN ('FULL_TIME', 'INTERNSHIP', 'BOTH')),
    stipend_ctc TEXT,
    description TEXT,
    deadline TIMESTAMPTZ NOT NULL,
    industry TEXT,
    location TEXT,
    about_company TEXT,
    selection_process TEXT,
    bond_details TEXT,
    criteria_details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'OPEN'
);

-- 3. Create eligibility_rules table
CREATE TABLE IF NOT EXISTS public.eligibility_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drive_id BIGINT REFERENCES public.placement_drives(id) ON DELETE CASCADE,
    min_cgpa NUMERIC DEFAULT 0,
    allowed_branches TEXT[] DEFAULT '{}',
    allowed_years TEXT[] DEFAULT '{}'
);

-- 4. Create drive_applications table
CREATE TABLE IF NOT EXISTS public.drive_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drive_id BIGINT REFERENCES public.placement_drives(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'APPLIED',
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(drive_id, student_id)
);

-- 5. Create events table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    venue TEXT,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    qr_refresh_interval INTEGER DEFAULT 10,
    created_by UUID REFERENCES public.user_profiles(id),
    entry_window_mins INTEGER DEFAULT 15,
    exit_window_mins INTEGER DEFAULT 15,
    attendance_phase TEXT DEFAULT 'CLOSED',
    session_state TEXT DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create qr_sessions table
CREATE TABLE IF NOT EXISTS public.qr_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create attendance_logs table
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
    qr_session_id BIGINT REFERENCES public.qr_sessions(id) ON DELETE SET NULL,
    device_hash TEXT,
    status TEXT DEFAULT 'ENTRY',
    scan_time TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, event_id)
);

-- 8. Create labs table
CREATE TABLE IF NOT EXISTS public.labs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    total_seats INTEGER NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Create assessments table
CREATE TABLE IF NOT EXISTS public.assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    date DATE,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    status TEXT DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Create assessment_eligibility table
CREATE TABLE IF NOT EXISTS public.assessment_eligibility (
    assessment_id BIGINT REFERENCES public.assessments(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    PRIMARY KEY (assessment_id, user_id)
);

-- 11. Create assessment_allocations table
CREATE TABLE IF NOT EXISTS public.assessment_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT REFERENCES public.assessments(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    lab_id BIGINT REFERENCES public.labs(id),
    seat_number INTEGER NOT NULL,
    allocated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(assessment_id, user_id)
);

-- Enable RLS (Optional but recommended for production)
-- ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
-- ... add more policies as needed
